import { motion } from 'framer-motion';
import { ListChecks, Lightbulb, FileText } from 'lucide-react';
import { fadeUp, staggerContainer } from '../animations/variants.js';
import PriorityBadge from '../components/workflow/PriorityBadge.jsx';
import { groupWorkflowByPhase } from '../components/workflow/executionPhases.js';

const mockWorkflow = {
  summary: "This is a preview of the structured execution plan generated by the FlowMind multi-agent system. The system parses raw input, extracts key objectives, and formulates a step-by-step roadmap for immediate execution.",
  key_insights: [
    "The primary objective is to finalize the hackathon MVP submission.",
    "Dependency: The Vercel deployment must occur before final recording.",
    "Constraint: Tight timeline requires skipping complex auth systems."
  ],
  action_items: [
    { title: "Validate final demo narrative", priority: "High Impact", execution_phase: "Research" },
    { title: "Finalize UI polish roadmap", priority: "High Impact", execution_phase: "Planning" },
    { title: "Deploy to Vercel", priority: "Quick Win", execution_phase: "Execution" },
    { title: "Review post-demo improvement queue", priority: "Long Term", execution_phase: "Optimization" }
  ]
};

export default function WorkflowResults() {
  const phaseGroups = groupWorkflowByPhase(mockWorkflow);

  return (
    <motion.div
      variants={staggerContainer}
      initial="hidden"
      animate="visible"
      className="min-w-0"
      style={{ width: 'min(100%, calc(100vw - 48px))' }}
    >
      
      <motion.div
        variants={fadeUp}
        className="mb-12 min-w-0 border-b border-white/[0.05] pb-6"
        style={{ maxWidth: 'calc(100vw - 48px)' }}
      >
        <h1 className="font-display text-3xl font-bold tracking-tight text-white">Execution Outputs</h1>
        <p className="mt-3 break-words text-[16px] text-white/50">Preview of the document-style execution plans and insights.</p>
      </motion.div>

      <motion.div
        variants={fadeUp}
        className="relative mx-auto w-full min-w-0 max-w-[800px] overflow-hidden rounded-[2.28rem] bg-[#04060b]/90 p-6 shadow-[inset_0_1px_1px_rgba(255,255,255,0.06),0_24px_80px_rgba(0,0,0,0.5)] ring-1 ring-white/[0.05] backdrop-blur-3xl sm:p-12"
        style={{ maxWidth: 'min(800px, calc(100vw - 48px))' }}
      >
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(255,255,255,0.06),transparent_30%)]" />
        
        <div className="relative min-w-0 space-y-14">
          
          <section>
            <div className="mb-4 flex items-center gap-3">
              <span className="grid h-8 w-8 place-items-center rounded-lg bg-emerald-500/10 text-emerald-200 ring-1 ring-emerald-500/20"><FileText size={16} /></span>
              <h2 className="font-display text-xl font-semibold text-white">Execution Plan Preview</h2>
            </div>
            <p className="break-words text-[16px] leading-relaxed text-white/60 sm:pl-11">{mockWorkflow.summary}</p>
          </section>

          <section>
            <div className="mb-6 flex items-center gap-3">
              <span className="grid h-8 w-8 place-items-center rounded-lg bg-purple-500/10 text-purple-200 ring-1 ring-purple-500/20"><Lightbulb size={16} /></span>
              <h3 className="font-display text-lg font-medium text-white">Key Insights</h3>
            </div>
            <ul className="space-y-4 sm:pl-11">
              {mockWorkflow.key_insights.map((insight, i) => (
                <li key={i} className="flex items-start gap-4 text-[15px] leading-relaxed text-white/80">
                  <span className="mt-2.5 h-1.5 w-1.5 shrink-0 rounded-full bg-cyan-300 shadow-[0_0_8px_rgba(34,211,238,0.8)]" />
                  <span className="min-w-0 break-words">{insight}</span>
                </li>
              ))}
            </ul>
          </section>

          <section>
            <div className="mb-6 flex items-center gap-3">
              <span className="grid h-8 w-8 place-items-center rounded-lg bg-blue-500/10 text-blue-200 ring-1 ring-blue-500/20"><ListChecks size={16} /></span>
              <h3 className="font-display text-lg font-medium text-white">Execution Pipeline</h3>
            </div>
            <div className="space-y-5 sm:pl-11">
              {phaseGroups.map((group) => (
                <div key={group.id} className="rounded-2xl bg-white/[0.02] p-4 ring-1 ring-white/[0.04]">
                  <div className="mb-3">
                    <p className="text-[12px] font-semibold text-white/90">{group.label}</p>
                    <p className="mt-1 text-xs leading-relaxed text-white/45">{group.description}</p>
                  </div>

                  <div className="space-y-3">
                    {group.action_items.map((item, i) => (
                      <div key={`${group.id}-${i}`} className="group relative flex w-full min-w-0 flex-col gap-3 overflow-hidden rounded-xl bg-white/[0.02] px-4 py-3 ring-1 ring-white/[0.04] transition-all hover:bg-white/[0.04] hover:ring-white/[0.08] sm:flex-row sm:items-center sm:justify-between">
                        <div className="flex min-w-0 items-center gap-4">
                          <div className="flex h-5 w-5 items-center justify-center rounded border border-white/10 transition-colors group-hover:border-cyan-300/40">
                            <div className="h-2 w-2 rounded-sm bg-cyan-300 opacity-0 transition-opacity group-hover:opacity-100" />
                          </div>
                          <span className="min-w-0 break-words text-[15px] font-medium text-white/90">{item.title}</span>
                        </div>
                        <PriorityBadge priority={item.priority} className="ml-9 self-start sm:ml-3 sm:self-center" />
                      </div>
                    ))}
                  </div>
                </div>
              ))}
                    </div>
          </section>

        </div>
      </motion.div>
      
    </motion.div>
  );
}
