import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { ListChecks, Lightbulb, FileText, ArrowLeft } from 'lucide-react';
import { fadeUp, staggerContainer } from '../animations/variants.js';
import PriorityBadge from '../components/workflow/PriorityBadge.jsx';
import { groupWorkflowByPhase } from '../components/workflow/executionPhases.js';

// Sample workflow for the standalone preview page.
// This page acts as a visual reference for the execution output format.
// Real workflow generation and full output happen on the Dashboard page.
const SAMPLE_WORKFLOW = {
  summary: "This is a sample execution plan generated by the FlowMind AI multi-agent system. Paste your own notes or goals into the Dashboard to generate a personalized plan powered by Google Gemini.",
  key_insights: [
    "The primary objective drives all downstream action items and workflow steps.",
    "Dependencies between phases must be resolved before execution can begin.",
    "Constraints and opportunities are surfaced by the Research Agent for planning context."
  ],
  action_items: [
    { title: "Define core objective and success criteria", priority: "Critical", execution_phase: "Research" },
    { title: "Map dependencies and identify blockers", priority: "High Impact", execution_phase: "Research" },
    { title: "Build execution roadmap with owners and timelines", priority: "High Impact", execution_phase: "Planning" },
    { title: "Prioritize quick wins for immediate momentum", priority: "Quick Win", execution_phase: "Planning" },
    { title: "Execute highest-priority action items first", priority: "Critical", execution_phase: "Execution" },
    { title: "Ship deliverables and validate outcomes", priority: "High Impact", execution_phase: "Execution" },
    { title: "Measure results and iterate on the system", priority: "Long Term", execution_phase: "Optimization" }
  ]
};

export default function WorkflowResults() {
  const phaseGroups = groupWorkflowByPhase(SAMPLE_WORKFLOW);

  return (
    <motion.div
      variants={staggerContainer}
      initial="hidden"
      animate="visible"
      className="min-w-0"
      style={{ width: 'min(100%, calc(100vw - 48px))' }}
    >
      
      <motion.div
        variants={fadeUp}
        className="mb-12 min-w-0 border-b border-white/[0.05] pb-6"
        style={{ maxWidth: 'calc(100vw - 48px)' }}
      >
        <div className="mb-4 inline-flex items-center gap-2 rounded-full bg-cyan-400/10 px-3 py-1.5 text-xs font-semibold text-cyan-200 ring-1 ring-cyan-400/20">
          <span className="h-1.5 w-1.5 rounded-full bg-cyan-400" />
          Sample Output
        </div>
        <h1 className="font-display text-3xl font-bold tracking-tight text-white">Execution Output Format</h1>
        <p className="mt-3 break-words text-[16px] text-white/50">
          This page shows a sample of the structured execution plan format.{' '}
          <Link to="/dashboard" className="text-cyan-300 underline underline-offset-2 hover:text-cyan-100 transition-colors">
            Go to the Dashboard
          </Link>{' '}
          to generate your own.
        </p>
      </motion.div>

      <motion.div
        variants={fadeUp}
        className="relative mx-auto w-full min-w-0 max-w-[800px] overflow-hidden rounded-[2.28rem] bg-[#04060b]/90 p-6 shadow-[inset_0_1px_1px_rgba(255,255,255,0.06),0_24px_80px_rgba(0,0,0,0.5)] ring-1 ring-white/[0.05] backdrop-blur-3xl sm:p-12"
        style={{ maxWidth: 'min(800px, calc(100vw - 48px))' }}
      >
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(255,255,255,0.06),transparent_30%)]" />
        
        <div className="relative min-w-0 space-y-14">
          
          <section>
            <div className="mb-4 flex items-center gap-3">
              <span className="grid h-8 w-8 place-items-center rounded-lg bg-emerald-500/10 text-emerald-200 ring-1 ring-emerald-500/20"><FileText size={16} /></span>
              <h2 className="font-display text-xl font-semibold text-white">Executive Summary</h2>
            </div>
            <p className="break-words text-[16px] leading-relaxed text-white/60 sm:pl-11">{SAMPLE_WORKFLOW.summary}</p>
          </section>

          <section>
            <div className="mb-6 flex items-center gap-3">
              <span className="grid h-8 w-8 place-items-center rounded-lg bg-purple-500/10 text-purple-200 ring-1 ring-purple-500/20"><Lightbulb size={16} /></span>
              <h3 className="font-display text-lg font-medium text-white">Key Insights</h3>
            </div>
            <ul className="space-y-4 sm:pl-11">
              {SAMPLE_WORKFLOW.key_insights.map((insight, i) => (
                <li key={i} className="flex items-start gap-4 text-[15px] leading-relaxed text-white/80">
                  <span className="mt-2.5 h-1.5 w-1.5 shrink-0 rounded-full bg-cyan-300 shadow-[0_0_8px_rgba(34,211,238,0.8)]" />
                  <span className="min-w-0 break-words">{insight}</span>
                </li>
              ))}
            </ul>
          </section>

          <section>
            <div className="mb-6 flex items-center gap-3">
              <span className="grid h-8 w-8 place-items-center rounded-lg bg-blue-500/10 text-blue-200 ring-1 ring-blue-500/20"><ListChecks size={16} /></span>
              <h3 className="font-display text-lg font-medium text-white">Execution Pipeline</h3>
            </div>
            <div className="space-y-5 sm:pl-11">
              {phaseGroups.map((group) => (
                <div key={group.id} className="rounded-2xl bg-white/[0.02] p-4 ring-1 ring-white/[0.04]">
                  <div className="mb-3">
                    <p className="text-[12px] font-semibold text-white/90">{group.label}</p>
                    <p className="mt-1 text-xs leading-relaxed text-white/45">{group.description}</p>
                  </div>

                  <div className="space-y-3">
                    {group.action_items.map((item, i) => (
                      <div key={`${group.id}-${i}`} className="group relative flex w-full min-w-0 flex-col gap-3 overflow-hidden rounded-xl bg-white/[0.02] px-4 py-3 ring-1 ring-white/[0.04] transition-all hover:bg-white/[0.04] hover:ring-white/[0.08] sm:flex-row sm:items-center sm:justify-between">
                        <div className="flex min-w-0 items-center gap-4">
                          <div className="flex h-5 w-5 items-center justify-center rounded border border-white/10 transition-colors group-hover:border-cyan-300/40">
                            <div className="h-2 w-2 rounded-sm bg-cyan-300 opacity-0 transition-opacity group-hover:opacity-100" />
                          </div>
                          <span className="min-w-0 break-words text-[15px] font-medium text-white/90">{item.title}</span>
                        </div>
                        <PriorityBadge priority={item.priority} className="ml-9 self-start sm:ml-3 sm:self-center" />
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </section>

          <section className="border-t border-white/[0.05] pt-8">
            <Link
              to="/dashboard"
              className="inline-flex items-center gap-2 rounded-xl bg-white/[0.04] px-5 py-3 text-[14px] font-semibold text-white/80 ring-1 ring-white/[0.08] transition-all hover:bg-white/[0.07] hover:text-white"
            >
              <ArrowLeft size={15} />
              Generate Your Workflow on the Dashboard
            </Link>
          </section>

        </div>
      </motion.div>
      
    </motion.div>
  );
}
