import { motion } from 'framer-motion';
import { ListChecks, Lightbulb, FileText } from 'lucide-react';
import { fadeUp, staggerContainer } from '../animations/variants.js';

const mockWorkflow = {
  summary: "This is a preview of the structured execution plan generated by the FlowMind multi-agent system. The system parses raw input, extracts key objectives, and formulates a step-by-step roadmap for immediate execution.",
  key_insights: [
    "The primary objective is to finalize the hackathon MVP submission.",
    "Dependency: The Vercel deployment must occur before final recording.",
    "Constraint: Tight timeline requires skipping complex auth systems."
  ],
  action_items: [
    { title: "Finalize UI Redesign", priority: "High" },
    { title: "Connect OpenAI endpoints", priority: "Critical" },
    { title: "Deploy to Vercel", priority: "High" },
    { title: "Record demo video", priority: "Medium" }
  ]
};

export default function WorkflowResults() {
  return (
    <motion.div variants={staggerContainer} initial="hidden" animate="visible">
      
      <motion.div variants={fadeUp} className="mb-12 border-b border-white/[0.05] pb-6">
        <h1 className="font-display text-3xl font-bold tracking-tight text-white">Execution Outputs</h1>
        <p className="mt-3 text-[16px] text-white/50">Preview of the document-style execution plans and insights.</p>
      </motion.div>

      <motion.div variants={fadeUp} className="relative mx-auto max-w-[800px] overflow-hidden rounded-[2.28rem] bg-[#04060b]/90 p-8 shadow-[inset_0_1px_1px_rgba(255,255,255,0.06),0_24px_80px_rgba(0,0,0,0.5)] ring-1 ring-white/[0.05] backdrop-blur-3xl sm:p-12">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(255,255,255,0.06),transparent_30%)]" />
        
        <div className="relative space-y-14">
          
          <section>
            <div className="mb-4 flex items-center gap-3">
              <span className="grid h-8 w-8 place-items-center rounded-lg bg-emerald-500/10 text-emerald-200 ring-1 ring-emerald-500/20"><FileText size={16} /></span>
              <h2 className="font-display text-xl font-semibold text-white">Execution Plan Preview</h2>
            </div>
            <p className="pl-11 text-[16px] leading-relaxed text-white/60">{mockWorkflow.summary}</p>
          </section>

          <section>
            <div className="mb-6 flex items-center gap-3">
              <span className="grid h-8 w-8 place-items-center rounded-lg bg-purple-500/10 text-purple-200 ring-1 ring-purple-500/20"><Lightbulb size={16} /></span>
              <h3 className="font-display text-lg font-medium text-white">Key Insights</h3>
            </div>
            <ul className="space-y-4 pl-11">
              {mockWorkflow.key_insights.map((insight, i) => (
                <li key={i} className="flex items-start gap-4 text-[15px] leading-relaxed text-white/80">
                  <span className="mt-2.5 h-1.5 w-1.5 shrink-0 rounded-full bg-cyan-300 shadow-[0_0_8px_rgba(34,211,238,0.8)]" />
                  {insight}
                </li>
              ))}
            </ul>
          </section>

          <section>
            <div className="mb-6 flex items-center gap-3">
              <span className="grid h-8 w-8 place-items-center rounded-lg bg-blue-500/10 text-blue-200 ring-1 ring-blue-500/20"><ListChecks size={16} /></span>
              <h3 className="font-display text-lg font-medium text-white">Action Items</h3>
            </div>
            <div className="space-y-3 pl-11">
              {mockWorkflow.action_items.map((item, i) => (
                <div key={i} className="group relative flex items-center justify-between overflow-hidden rounded-2xl bg-white/[0.02] px-5 py-4 ring-1 ring-white/[0.04] transition-all hover:bg-white/[0.04] hover:shadow-[0_8px_20px_rgba(0,0,0,0.2)] hover:ring-white/[0.08]">
                  <div className="flex items-center gap-4">
                    <div className="flex h-5 w-5 items-center justify-center rounded border border-white/10 transition-colors group-hover:border-cyan-300/40">
                      <div className="h-2 w-2 rounded-sm bg-cyan-300 opacity-0 transition-opacity group-hover:opacity-100" />
                    </div>
                    <span className="text-[15px] font-medium text-white/90">{item.title}</span>
                  </div>
                  <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-semibold tracking-wide uppercase ${item.priority === 'Critical' ? 'bg-red-500/10 text-red-200 ring-1 ring-red-500/20' : item.priority === 'High' ? 'bg-amber-500/10 text-amber-200 ring-1 ring-amber-500/20' : 'bg-blue-500/10 text-blue-200 ring-1 ring-blue-500/20'}`}>
                    {item.priority === 'Critical' && <span className="status-live h-1.5 w-1.5 rounded-full bg-red-400" />}
                    {item.priority}
                  </span>
                </div>
              ))}
            </div>
          </section>

        </div>
      </motion.div>
      
    </motion.div>
  );
}
